//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseSale
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public int promogroup_id { get; set; }
        public int period_id { get; set; }
        public double value { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PromoGroup PromoGroup { get; set; }
        public virtual Period Period { get; set; }
    }
}
