//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersDetail
    {
        public int id { get; set; }
        public string shipto { get; set; }
        public string soldto { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public int customer_id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
