//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsPrice
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public System.DateTime date_from { get; set; }
        public System.DateTime date_to { get; set; }
        public int currency_id { get; set; }
        public double gsv { get; set; }
        public double pc { get; set; }
        public double cc { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Product Product { get; set; }
    }
}
