//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;


    public partial class PromotionsDetail
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int promotion_id { get; set; }
        public int volume { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:P2}", ApplyFormatInEditMode = true)]
        public double discount_on { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:P2}", ApplyFormatInEditMode = true)]
        public double discount_off { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:P2}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> te_on { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:P2}")]
        public Nullable<decimal> te_off { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:P2}")]
        public Nullable<decimal> edlp { get; set; }

        public virtual Product Product { get; set; }

        //public int GSV { get { return volume * Product.casecount; } }

        //[ForeignKey("promotion_id")]
        public virtual Promotion Promotion { get; set; }
    }
}
