//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsDetail
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int promotion_id { get; set; }
        public int volume { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:P2}", ApplyFormatInEditMode = true)]
        public double discount_on { get; set; }
        [System.ComponentModel.DataAnnotations.DisplayFormat(DataFormatString = "{0:P2}", ApplyFormatInEditMode = true)]
        public double discount_off { get; set; }
        public Nullable<decimal> te_on { get; set; }
        public Nullable<decimal> te_off { get; set; }
        public Nullable<decimal> edlp { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
