//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string name { get; set; }
        public int usergroup_id { get; set; }
        public string mail { get; set; }
        public bool customer_service_notification { get; set; }
        public bool logistic_notification { get; set; }
        public bool management_notification { get; set; }
        public bool admin_notofication { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
    }
}
