//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFixedTE
    {
        public int customer_id { get; set; }
        public int segment_id { get; set; }
        public int year { get; set; }
        public double on_te { get; set; }
        public double off_te { get; set; }
    }
}
