//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPromotionsCalculation
    {
        public int customer_id { get; set; }
        public Nullable<int> volume { get; set; }
        public Nullable<double> gsv { get; set; }
        public Nullable<double> niv { get; set; }
        public Nullable<double> nsv { get; set; }
        public Nullable<double> te { get; set; }
        public Nullable<double> te_perc { get; set; }
        public Nullable<double> mmac { get; set; }
        public Nullable<double> mmac_perc { get; set; }
    }
}
